// imports ================================================== //
import AppearanceProvider from "@/app/providers/AppearanceProvider";
import { Inter } from "next/font/google";
import type { ReactNode, FC } from "react";
import "@/shared/styles/index.css";
import ContainerApp from "@/entities/ContainerApp";
import HeaderApp from "@/widgets/HeaderApp";
import Main from "@/shared/components/Main";
import SwitchColorTheme from "@/features/SwitchColorTheme";

// types ==================================================== //
interface Props {
	children: ReactNode | ReactNode[];
}
type RootLayoutType = FC<Readonly<Props>>;

// constants ================================================ //
const InterFont = Inter({
	subsets: ["cyrillic", "latin"],
	display: "swap",
});
const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

// main ===================================================== //
const RootLayout: RootLayoutType = ({ children }) => (
	<html lang="ru">
		<body className={InterFont.className}>
				<AppearanceProvider>
					<ContainerApp>
						<HeaderApp />
						<Main>
							{children}
						</Main>
						<div style={{ margin: "30px auto", textAlign: "center" }}>
							<SwitchColorTheme />
						</div>
					</ContainerApp>
				</AppearanceProvider>
			<div id="popup_container"></div>
		</body>
	</html>
);

// exports ================================================== //
export default RootLayout;
export { metadata };
